import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const scriptsDir = path.join(repoRoot, ".pipemd", "scripts");
const fixturesDir = path.join(repoRoot, "tests", "fixtures");
const baselineFile = path.join(here, "intrinsic-baseline.json");
const reportFile = path.join(repoRoot, "BENCHMARKS.md");

const TOKEN_BUDGET = 2000;
const LATENCY_BUDGET_MS = 5000;
const RATCHET_GROWTH_PCT = 15;
const RATCHET_SHRINK_PCT = 50;

interface BenchResult {
  fixture: string;
  script: string;
  bytes: number;
  tokens: number;
  ms: number;
  error?: string;
}

function listScripts(): string[] {
  const results: string[] = [];
  for (const cat of ["architecture", "project", "git", "quality"]) {
    const catDir = path.join(scriptsDir, cat);
    if (!fs.existsSync(catDir)) continue;
    for (const file of fs.readdirSync(catDir)) {
      if (file.endsWith(".sh") || file.endsWith(".mjs")) {
        results.push(`${cat}/${file}`);
      }
    }
  }
  return results;
}

function listFixtures(): string[] {
  return fs.readdirSync(fixturesDir).filter((d) => {
    const stat = fs.statSync(path.join(fixturesDir, d));
    return stat.isDirectory();
  });
}

function runScript(scriptRel: string, cwd: string): BenchResult {
  const scriptPath = path.join(scriptsDir, scriptRel);
  const start = Date.now();
  try {
    const bin = scriptPath.endsWith(".mjs") ? "node" : "bash";
    const args = scriptPath.endsWith(".mjs") ? [scriptPath] : [scriptPath];
    const stdout = execFileSync(bin, args, {
      encoding: "utf-8",
      timeout: LATENCY_BUDGET_MS,
      cwd,
      env: { ...process.env, PMD_TOKEN_PROFILE: "medium" },
    });
    const ms = Date.now() - start;
    const bytes = Buffer.byteLength(stdout, "utf-8");
    return { fixture: path.basename(cwd), script: scriptRel, bytes, tokens: Math.round(bytes / 4), ms };
  } catch (err: unknown) {
    const e = err as { killed?: boolean; signal?: string };
    const ms = Date.now() - start;
    const error = e.killed || e.signal === "SIGTERM" ? "timeout" : (err as Error).message?.slice(0, 80) || "error";
    return { fixture: path.basename(cwd), script: scriptRel, bytes: 0, tokens: 0, ms, error };
  }
}

function loadBaseline(): Record<string, BenchResult> | null {
  try {
    const raw = fs.readFileSync(baselineFile, "utf-8");
    const arr = JSON.parse(raw) as BenchResult[];
    const map: Record<string, BenchResult> = {};
    for (const r of arr) map[`${r.fixture}/${r.script}`] = r;
    return map;
  } catch { return null; }
}

const updateFlag = process.argv.includes("--update");
const baseline = loadBaseline();
const scripts = listScripts();
const fixtures = listFixtures();

const results: BenchResult[] = [];
for (const fixture of fixtures) {
  const cwd = path.join(fixturesDir, fixture);
  for (const script of scripts) {
    const result = runScript(script, cwd);
    results.push(result);
  }
}

if (updateFlag || !baseline) {
  fs.writeFileSync(baselineFile, JSON.stringify(results, null, 2) + "\n");
  console.log(`Baseline written to ${path.relative(repoRoot, baselineFile)} (${results.length} entries)`);
} else {
  let violations = 0;
  for (const r of results) {
    const key = `${r.fixture}/${r.script}`;
    const prev = baseline[key];
    if (!prev) continue;
    if (r.error) {
      console.log(`⚠ ${key}: ${r.error}`);
      violations++;
      continue;
    }
    if (r.tokens > TOKEN_BUDGET) {
      console.log(`⚠ ${key}: ${r.tokens} tokens exceeds budget (${TOKEN_BUDGET})`);
      violations++;
      continue;
    }
    if (prev.tokens > 0) {
      const growth = ((r.tokens - prev.tokens) / prev.tokens) * 100;
      const shrink = ((prev.tokens - r.tokens) / prev.tokens) * 100;
      const absGrowth = r.tokens - prev.tokens;
      if (prev.tokens >= 50 && growth > RATCHET_GROWTH_PCT && absGrowth > 50) {
        console.log(`⚠ ${key}: ${growth.toFixed(0)}% token growth (${prev.tokens} → ${r.tokens}, +${absGrowth})`);
        violations++;
      }
      if (prev.tokens >= 50 && shrink > RATCHET_SHRINK_PCT && r.tokens === 0) {
        console.log(`⚠ ${key}: output disappeared (${prev.tokens} → 0) — possible failure`);
        violations++;
      }
    }
  }
  if (violations > 0) {
    console.log(`\n${violations} ratchet violation(s). Run 'pnpm bench --update' to refresh baseline.`);
    process.exit(1);
  } else {
    console.log(`✔ ${results.length} entries checked — no ratchet violations`);
  }
}

const lines: string[] = [
  "# PipeMD Intrinsic Benchmarks",
  "",
  "> Auto-generated by `pnpm bench`. Do not edit manually.",
  `> Last updated: ${new Date().toISOString()}`,
  "",
  "| Fixture | Script | Bytes | Tokens | Latency (ms) |",
  "|---------|--------|------:|-------:|-------------:|",
];

for (const r of results) {
  const err = r.error ? ` ⚠ ${r.error}` : "";
  lines.push(`| ${r.fixture} | \`${r.script}\` | ${r.bytes} | ${r.tokens} | ${r.ms}${err} |`);
}

lines.push("");
fs.writeFileSync(reportFile, lines.join("\n"));
console.log(`Report written to ${path.relative(repoRoot, reportFile)}`);
